[project]
name = "data-engineering-course-batch-3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sanil shakya", email = "sanilshakya9@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "psycopg2-binary>=2.9.12",
    "python-dotenv>=1.2.2",
]

[project.scripts]
data-engineering-course-batch-3 = "data_engineering_course_batch_3:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
